name = "Comfort"
author = "Sindercube"
version = "null"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8214f77acb795297d26d9cb528e9295c6d1feb235e49237f3c84af86b1a77561"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
