name = "Comfort"
author = "Sindercube"
version = "null"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14c9b3eb00e1873a131853ba284367010e0ff01327a0643e25448c5470bee83e"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
