# Enable forge global version checking
versionCheck = false
# does the splashscreen run
splashscreen = true
defaultConfigPath = "server_config"
# max threads for parallel loading : -1 uses Runtime#availableProcessors
maxThreads = -1

